-- MySQL Script generated by MySQL Workbench
-- Sun Jul  4 17:11:40 2021
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
-- -----------------------------------------------------
-- Schema dbvacations
-- -----------------------------------------------------

-- -----------------------------------------------------
-- Schema dbvacations
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `dbvacations` DEFAULT CHARACTER SET utf8mb4 ;
USE `dbvacations` ;

-- -----------------------------------------------------
-- Table `dbvacations`.`categories`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`categories` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `category` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 6
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`destinations`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`destinations` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `destination` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 5
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`users`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`users` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `first_name` VARCHAR(255) NULL DEFAULT NULL,
  `last_name` VARCHAR(255) NULL DEFAULT NULL,
  `mail` VARCHAR(255) NULL DEFAULT NULL,
  `telephone` INT(11) NULL DEFAULT NULL,
  `avatar` VARCHAR(255) NULL DEFAULT NULL,
  `password` VARCHAR(255) NULL DEFAULT NULL,
  `admin` TINYINT(4) NULL DEFAULT NULL,
  `casa` TINYINT(4) NULL DEFAULT NULL,
  `departamento` TINYINT(4) NULL DEFAULT NULL,
  `hotel` TINYINT(4) NULL DEFAULT NULL,
  `hosteria` TINYINT(4) NULL DEFAULT NULL,
  `aparts` TINYINT(4) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`properties`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`properties` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `user_id` INT(11) NULL DEFAULT NULL,
  `destination_id` INT(11) NULL DEFAULT NULL,
  `address` VARCHAR(255) NULL DEFAULT NULL,
  `wifi` TINYINT(4) NULL DEFAULT NULL,
  `pool` TINYINT(4) NULL DEFAULT NULL,
  `parking` TINYINT(4) NULL DEFAULT NULL,
  `barbecue` TINYINT(4) NULL DEFAULT NULL,
  `price` DECIMAL(10,0) NULL DEFAULT NULL,
  `category_id` INT(11) NULL DEFAULT NULL,
  `n_of_people` INT(11) NULL DEFAULT NULL,
  `activated` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  INDEX `destination_id` (`destination_id` ASC) VISIBLE,
  INDEX `category_id` (`category_id` ASC) VISIBLE,
  CONSTRAINT `properties_ibfk_1`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbvacations`.`users` (`id`),
  CONSTRAINT `properties_ibfk_2`
    FOREIGN KEY (`destination_id`)
    REFERENCES `dbvacations`.`destinations` (`id`),
  CONSTRAINT `properties_ibfk_3`
    FOREIGN KEY (`category_id`)
    REFERENCES `dbvacations`.`categories` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 4
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`images`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`images` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `property_id` INT(11) NULL DEFAULT NULL,
  `image_name` VARCHAR(255) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `property_id` (`property_id` ASC) VISIBLE,
  CONSTRAINT `images_ibfk_1`
    FOREIGN KEY (`property_id`)
    REFERENCES `dbvacations`.`properties` (`id`))
ENGINE = InnoDB
AUTO_INCREMENT = 10
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`orders`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`orders` (
  `id` INT(11) NOT NULL AUTO_INCREMENT,
  `property_id` INT(11) NULL DEFAULT NULL,
  `user_id` INT(11) NULL DEFAULT NULL,
  `check_in` DATETIME NULL DEFAULT NULL,
  `check_out` DATETIME NULL DEFAULT NULL,
  `n_of_people` INT(11) NULL DEFAULT NULL,
  `credit_card` VARCHAR(255) NULL DEFAULT NULL,
  `expiry_date` DATETIME NULL DEFAULT NULL,
  `comment` VARCHAR(255) NULL DEFAULT NULL,
  `rating` INT(11) NULL DEFAULT NULL,
  `createdAt` DATETIME NOT NULL,
  `updatedAt` DATETIME NOT NULL,
  PRIMARY KEY (`id`),
  INDEX `property_id` (`property_id` ASC) VISIBLE,
  INDEX `user_id` (`user_id` ASC) VISIBLE,
  CONSTRAINT `orders_ibfk_1`
    FOREIGN KEY (`property_id`)
    REFERENCES `dbvacations`.`properties` (`id`),
  CONSTRAINT `orders_ibfk_2`
    FOREIGN KEY (`user_id`)
    REFERENCES `dbvacations`.`users` (`id`))
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8mb4;


-- -----------------------------------------------------
-- Table `dbvacations`.`sequelizemeta`
-- -----------------------------------------------------
CREATE TABLE IF NOT EXISTS `dbvacations`.`sequelizemeta` (
  `name` VARCHAR(255) NOT NULL,
  PRIMARY KEY (`name`),
  UNIQUE INDEX `name` (`name` ASC) VISIBLE)
ENGINE = InnoDB
DEFAULT CHARACTER SET = utf8
COLLATE = utf8_unicode_ci;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
